version: "3.9"
services:
  redis:
    image: redis
    expose:
      - 6379
    volumes:
      - ./tmp/redis:/data

  server:
    build: .
    expose:
      - 4001
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`side.recodable.io`)"
      - "traefik.http.routers.server.tls=true"
      - "traefik.http.routers.server.tls.certresolver=lets-encrypt"

  traefik:
    image: traefik:2.1
    restart: always
    ports:
      - "4001:4001"
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
