version: "3.9"
services:
  redis:
    image: redis
    networks:
      - "internal"
    expose:
      - 6379
    volumes:
      - ./tmp/redis:/data
    labels:
      - "traefik.enable=false"

  server:
    build: .
    ports:
      - "4001:8000"
    depends_on:
      - redis
    networks:
      - "web"
      - "internal"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.contribute-solidjs.rule=Host(`side.recodable.io`)"
      - "traefik.http.routers.contribute-solidjs.tls=true"
      - "traefik.http.routers.contribute-solidjs.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=web"
      - "traefik.port=80"

networks:
  web:
    external: true
  internal:
    external: false
