version: "3.9"
services:
  redis:
    image: redis
    expose:
      - 6379
    volumes:
      - ./tmp/redis:/data

  server:
    build: .
    ports:
      - "4001:8000"
    depends_on:
      - redis
